// src/app/layout.js
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import './lawyer.css';

import NavbarUI from './components-ui/NavbarUI';
import FooterUI from './components-ui/FooterUI';
import Container from 'react-bootstrap/Container';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`d-flex flex-column min-vh-100`}>
        <NavbarUI />
        <main className="flex-grow-1">
          <Container>
            {children}
          </Container>
        </main>
        <FooterUI />
      </body>
    </html>
  );
}
